server:
  port: 8080
  error:
    include-message: always
spring:
  output:
    ansi:
      enabled: always
  sql:
    init:
      platform: postgresql
      mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    ## Logging settings
debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR